/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import Image from "next/image";
import logo from "../public/images/logo.svg";
import menu from "../public/images/icon-menu.svg";
import HeroMobile from "../public/images/image-hero-mobile.png";
import Audiophile from "../public/images/client-audiophile.svg";
import Databiz from "../public/images/client-databiz.svg";
import Maker from "../public/images/client-maker.svg";
import Meet from "../public/images/client-meet.svg";

export default function Home() {
  return (
    <div className="min-h-screen bg-white text-black">
      <Head>
        <title>Snap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Epilogue:wght@500;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        <section className="p-5 text-medium-gray font-medium">
          <nav>
            <div className="flex justify-between">
              <ul className="flex gap-12">
                <li>
                  <Image className="cursor-pointer" src={logo} alt="" />
                </li>
                <li className="hidden lg:flex hover:text-black">
                  <a href="#">Features</a>
                </li>
                <li className="hidden lg:flex hover:text-black">
                  <a href="#">Company</a>
                </li>
                <li className="hidden lg:flex hover:text-black">
                  <a href="#">Careers</a>
                </li>
                <li className="hidden lg:flex hover:text-black">
                  <a href="#">About</a>
                </li>
              </ul>
              <ul className="flex gap-12">
                <li className="hidden lg:flex hover:text-black">
                  <a href="#">Login</a>
                </li>
                <li className="hidden lg:flex hover:text-black">
                  <a
                    href="#"
                    className="rounded-lg border border-black px-3 py-1 relative bottom-1"
                  >
                    Register
                  </a>
                </li>
                <li className="lg:hidden cursor-pointer">
                  <Image className="" src={menu} alt="" />
                </li>
              </ul>
            </div>
          </nav>
        </section>

        <section>
          <div>
            <Image src={HeroMobile} alt="" className="min-w-full" />
            <div className="text-center">
              <h1 className="text-4xl font-epilogue font-bold mt-10">Make remote work</h1>
              <p className="text-medium-gray font-epilogue my-10 mb-12">
                Get your team in sync, no matter your location. Streamline
                processes, create team rituals, and watch productivity soar.
              </p>
              <a href="#" className="py-3 px-5 rounded-xl bg-black border border-black text-white font-epilogue hover:bg-white hover:text-black">Learn More</a>
                <ul className="flex justify-evenly mt-16">
                  <li>
                    <Image alt="" src={Databiz} />
                  </li>
                  <li>
                    <Image alt="" src={Audiophile} />
                  </li>
                  <li>
                    <Image alt="" src={Meet} />
                  </li>
                  <li>
                    <Image alt="" src={Maker} />
                  </li>
                </ul>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
